[package]
name = "ipc_poc"
version = "0.1.0"
authors = ["Mateusz Górski <gorski.mateusz@protonmail.ch>"]

[dependencies]
clap = "2.32.0"
protobuf = "2"
commons = { path = "../commons" }
grpc = "0.6.1"
futures         = "0.1.8"
futures-cpupool = "0.1.8"
